- name: Check if Dropbox is already there
  stat:
    path: "~{{dropbox_install_user}}/Dropbox"
  register: dbox_inst

- block:
  - name: (user {{dropbox_install_user}}) - Download & unarchive the Dropbox bundle
    unarchive:
      remote_src: "yes"
      src: "{{ dropbox_download_url }}"
      dest: "~{{ dropbox_install_user }}/"

  - name: (user {{dropbox_install_user}}) - Run the daemon (install)
    shell: "~{{dropbox_install_user}}/.dropbox-dist/dropboxd 2>&1 > ~/tmp-ansible-dropbox-install-link_{{dropbox_install_user}}"
    async: 180
    poll: 0

  - name: (user {{dropbox_install_user}}) - Wait for dropboxd to write to file
    wait_for:
      path: ~/tmp-ansible-dropbox-install-link_{{dropbox_install_user}}
      search_regex: "nonce"
      timeout: 30
    ignore_errors: true

  - name: (user {{dropbox_install_user}}) - Learn Dropbox Account-Link URL
    shell: cat ~/tmp-ansible-dropbox-install-link_{{dropbox_install_user}}
    register: inst_link

  - name: (user {{dropbox_install_user}}) - Remove account-link tmpfile
    file:
      path: ~/tmp-ansible-dropbox-install-link_{{dropbox_install_user}}
      state: "absent"

  - name: "(user {{dropbox_install_user}}) - ** LOG IN TO THIS URL WITHIN 3 MINUTES TO CONNECT THE DROPBOX ACCOUNT TO {{dropbox_install_user}}@{{ansible_hostname}} **"
    debug:
      msg: "{{ inst_link.stdout_lines[1] | default('NONE FOUND') }}"
    when: (inst_link.stdout_lines | default([])) | length > 0
  when: (ansible_check_mode == false) and (not dbox_inst.stat.exists)
  become: "yes"
  become_user: "{{dropbox_install_user}}"