---
- name: Install req'd dependencies
  apt:
    name: "{{ item }}"
    state: "present"
  loop:
  - "libglapi-mesa"
  - "libxdamage1"
  - "libxfixes3"

- include_tasks: do-install.yml
  loop: "{{ dropbox_install_users }}"
  loop_control:
    loop_var: dropbox_install_user